### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by nirvdrum** [jkrall/analytical#26]
It'd be very helpful if there were a changelog indicating what's different from release-to-release.  I'm looking to upgrade an app from Rails 2.3 -> 3.0 and I can't tell which version of analytical I should target.  The latest doesn't work with Rails 3 and appears not have for for several versions now.  Beyond that, it'd help let me know whether a new release is worth upgrading to or not.

**Comment by jkrall** [comment]
Sorry to hear you're having trouble.  I'm running analytical in production
on 3.1, and I've talked to a few people who are successfully running it on
3.0.

Can you explain what trouble you are having?  I'd prefer to fix it and make
it compatible...

(That said, yes, a changelog would be nice.  I'll try to be better about
that.  However, there haven't been _that_ many commits... )

**Comment by nirvdrum** [comment]
I'm currently getting tripped up by issue #19.

Prior to this upgrade I had been using the 2.x series.  You're right, there aren't that many commits.  But the message rarely tells the whole story, so I have to look at the diff in many cases.  And I'm still not sure what the reason for the big jump to 3.0 was, but I imagine there is one.

**Comment by jkrall** [comment]
Hmm, yep, sorry about that.  Been so busy at work lately that this issue
slipped my mind.  I'll take a look at it now and see if I can come up with a
fix.

The big change w/ 3.0 was adding the javascript helpers that get loaded by
default.

Of course, you are right, I'll add a Changelog and try to add some of the
change history as well... so that it's easier for people to tell what
happened.
