### ISSUE TITLE
Rails 3.0.9 dependency

### ISSUE THREAD

**Issue by jocubeit** [jkrall/analytical#45]
Is there any reason this gem has a dependency on Rails 3.0.9? Does this mean if I'm running Rails 3.2.7 installing this gem will also install Rails 3.0.9?

**Comment by jkrall** [comment]
No reason... that's the last version it was tested & updated against.  I don't have any reason to believe it wouldn't work with 3.2, but there might be some issues to resolve w/ the asset pipeline or something.

Feel free to submit a patch.

**Comment by sfsekaran** [comment]
Thankfully, that's only a "development" dependency. We've been using analytical with Rails 3.2.x in production for quite some time here at Topspin without a hitch. It would be nice to update the specs to test with multiple Rails versions, but for now I'm going to close this request, since that's a separate issue.
