### ISSUE TITLE
TrackSubmit

### ISSUE THREAD

**Issue by gyarra** [jkrall/analytical#58]
Hi, 

First, thanks for the gem. It's pretty awesome.

I'm using KissMetrics and would like to call TrackSubmit. I don't see a way to do that with the current code base. It seems pretty easy to add. If I add TrackSubmit to KissMetrics, and perhaps the corollary track_forms to MixPanel, would you accept the pull request?

Thanks,
Gabe

**Comment by jkrall** [comment]
Sure thing.

I don't know kissmetrics well anymore, so I'm not familiar with
TrackSubmit.... But if you can try to make new analtyical methods
general-purpose
so that other providers with similar functionality can implement them as
well, that'd be awesome.

One goal of analytical is to make it easy to switch or try out multiple
services.

**Comment by gyarra** [comment]
Awesome, will do.

I really like Analytical and am happy to contribute as much as I can. I've
been looking for a good project to get into.

**Comment by gyarra** [comment]
Hi,

I created a wiki page with documentation for using KissMetrics with Analytical. Is this something that you think would be useful?
https://github.com/gyarra/analytical/wiki/KissMetrics

**Comment by sfsekaran** [comment]
Please open a pull request for each library you're updating, if you get around to it. I believe Kissmetrics was updated since this was opened, FYI.
